### ISSUE TITLE
Part of response coming up NULL

### ISSUE THREAD

**Issue by darkdemon28** [Wifsimster/petrus#3]
Hey. I thought I'd open this because the response from a search is almost complete, however the 'name' part coming up NULL. Any chance you can look into this and update so it works fully please?

Thanks!

**Comment by Wifsimster** [comment]
Sorry for the delay, i'll look into this right now !

**Comment by Wifsimster** [comment]
Replaced jsdom with puppeteer dependency to make Petrus compliant with new TPB site.
